# Location not final and subject to change!
FROM quay.io/fedora-ostree-desktops/kinoite:39

LABEL org.opencontainers.image.title="Fedora Kinoite Minecraft"
LABEL org.opencontainers.image.description="Customized image of Fedora Kinoite with Minecraft"
LABEL org.opencontainers.image.source="https://github.com/heyste/fedora-kinoite"
LABEL org.opencontainers.image.licenses="MIT"

RUN rpm-ostree install \
        bwm-ng \
        distrobox \
        htop \
        igt-gpu-tools \
        iotop \
        iwd \
        kitty \
        krb5-workstation \
        libvirt-daemon \
        libvirt-daemon-config-network \
        libvirt-daemon-driver-interface \
        libvirt-daemon-driver-network \
        libvirt-daemon-driver-nwfilter \
        libvirt-daemon-driver-qemu \
        libvirt-daemon-driver-secret \
        libvirt-daemon-driver-storage-core \
        libvirt-dbus \
        netcat \
        qemu-kvm \
        sysprof \
        vim \
        wireguard-tools \
        zsh \
    && \
    systemctl enable libvirtd.socket \
    && \
    rm -rf /var/lib/unbound/root.key


# A helper to set ARCH_TYPE and ARCH_TYPE2
COPY arch-helper.sh /usr/bin/arch-helper.sh

# Install Java
RUN curl -L https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz \
    | tar --directory /tmp --extract --ungzip \
  && mv /tmp/jdk-17.0.10 /usr/bin/jdk-17

# Update PATH include java binary
RUN echo 'export PATH=$PATH:/usr/bin/jdk-17/bin' >> /etc/skel/.bashrc

# Copy custom config to /usr & /etc
COPY usr usr
COPY etc etc

RUN ostree container commit
